import { League_Spartan } from "next/font/google";
import "./globals.css";
import localFont from "@next/font/local";
import Nav from "./components/nav";

const league = League_Spartan({ subsets: ["latin"], weight: "400" });
const lancelot = localFont({
  src: [
    {
      path: "../../public/fonts/Lancelot.ttf",
      weight: "400",
    },
  ],
  variable: "--font-lancelot",
});
const clash = localFont({
  src: [
    {
      path: "../../public/fonts/ClashDisplay-Semibold.ttf",
      weight: "400",
    },
  ],
  variable: "--font-clash",
});

export const metadata = {
  title: "Sami's portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${clash.variable} ${league.className} ${lancelot.variable}`}
    >
      <body>
        <Nav />
        {children}
      </body>
    </html>
  );
}
